options:
  inventory-title: Spawner Shop
  sign-title: '&9[SpawnerShop]'
  open-message: '&9Opening the shop inventory.'
  sign-success: '&9You have sucessfully created a SpawnerShop sign!'
  inventory-size: 54
  no-permission: '&9You do not have permission to do that.'
  cooldown: 10
  cooldown-message: '&9You must wait {time} seconds before using that command again.'
  currency-sign: $
  reload-success: '&9You have successfully reloaded the plugin.'
  prefix: '&7[&cSS&7]'
  no-money: '&9You do not have the {currency}{money} required to purchase that!'
  sale-message: '&9{currency}{amount} has been taken from your account.'
  buy-message: '&9{currency}{amount} has been deposited into your account.'
  no-spawner-selected: '&9Please choose a spawner type!'
  no-spawner-sell: '&9You do not have a {spawner} Spawner to sell.'
  invalid-price: '&9You have either not entered a price, or entered one incorrectly. The price has been set to the one specified in the config!'
  language: 'ENG'