name: SpawnerShop
version: 4.1
main: com.ctooley.plugins.SpawnerShop
depend: [Vault]
api-version: 1.15
commands:
  spawners:
    description: This is the main command!
    usage: /<command> 
permissions:
  spawnershop.use:
    description: Gives access to the command /spawners
    default: true
  spawnershop.reload:
    description: Gives access to /spawners reload which allows you to reload the configuration file.
    default: false
  spawnershop.signs.use:
    description: Gives access to use the SpawnerShop signs!
    default: true
  spawnershop.signs.create:
    description: Gives access to create a SpawnerShop sign!
    default: false